spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  h2:
    console:
      enabled: true
  sql:
     init:
       mode: never
       encoding: UTF-8
  jpa:
    generate-ddl: false #true
    show_sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: on
  data:
    rest:
      base-path: /api

logging:
  level:
    org:
      springframework:
        orm:
          jpa: INFO
          JpaTransactionManager: DEBUG
      transaction: INFO
      interceptor: TRACE

---
spring:
  config:
    activate:
      on-profile: "ci, test"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:shareit
    username: share
    password: it
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always