create table if not exists USERS
(
    ID    BIGINT generated by default as identity
        primary key,
    EMAIL CHARACTER VARYING(255)
        constraint UK_EMAIL
            unique,
    NAME  CHARACTER VARYING(255)
);

create table if not exists REQUESTS
(
    ID           BIGINT generated by default as identity
        primary key,
    CREATED      TIMESTAMP,
    DESCRIPTION  CHARACTER VARYING(255),
    REQUESTOR_ID BIGINT,
    constraint FK_REQUESTS_USERS_ID
        foreign key (REQUESTOR_ID) references USERS
);

create table if not exists ITEMS
(
    ID          BIGINT generated by default as identity
        primary key,
    AVAILABLE   BOOLEAN,
    DESCRIPTION CHARACTER VARYING(255),
    NAME        CHARACTER VARYING(255),
    OWNER_ID    BIGINT,
    REQUEST_ID  BIGINT,
    constraint FK_ITEMS_USERS_ID
        foreign key (OWNER_ID) references USERS,
    constraint FK_ITEMS_REQUESTS_ID
        foreign key (REQUEST_ID) references REQUESTS
);

create table if not exists  COMMENTS
(
    ID        BIGINT generated by default as identity
        primary key,
    CREATED   TIMESTAMP,
    TEXT      CHARACTER VARYING(1000),
    AUTHOR_ID BIGINT,
    ITEM_ID   BIGINT,
    constraint FK_COMMENTS_ITEMS_ID
        foreign key (ITEM_ID) references ITEMS,
    constraint FK_COMMENTS_USERS_ID
        foreign key (AUTHOR_ID) references USERS
);

create table if not exists  BOOKINGS
(
    ID        BIGINT generated by default as identity
        primary key,
    ENDING    TIMESTAMP,
    START     TIMESTAMP,
    STATUS    CHARACTER VARYING(255),
    BOOKER_ID BIGINT,
    ITEM_ID   BIGINT,
    constraint FK_BOOKINGS_ITEMS_ID
        foreign key (ITEM_ID) references ITEMS,
    constraint FK_BOOKINGS_USERS_ID
        foreign key (BOOKER_ID) references USERS
);